config/routes.rb
ReSafari::Application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  root 'welcome#index'

  resources :friends

  

end

app/models/friend.rb
class Friend < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
        :omniauthable, :omniauth_providers => [:twitter, :facebook, :google_oauth2]

has_many :friends


  def self.find_for_twitter_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first_or_initialize
    user.name = auth.info.name
    user.provider = auth.provider
    user.uid = auth.uid
    user.email = auth.uid+"@twitter.com"
    user.password = Devise.friendly_token[0,20]
    user.oauth_token = auth.credentials.token
    user.oauth_secret = auth.credentials.secret
    user.save!
    user.add_twitter_friends
    user
  end

  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first_or_initialize
    user.name = auth.info.name
    user.provider = auth.provider
    user.uid = auth.uid
    user.email = auth.info.email
    user.password = Devise.friendly_token[0,20]
    user.oauth_token = auth.credentials.token
    # user.oauth_secret = auth.credentials.secret
    user.save!
    user.add_facebook_friends
    user
  end

  def self.find_for_google_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first_or_initialize
    user.name = auth.info.name
    user.provider = auth.provider
    user.uid = auth.uid
    user.email = auth.info.email
    user.password = Devise.friendly_token[0,20]
    user.oauth_token = auth.credentials.token
    # user.oauth_secret = auth.credentials.refresh_token
    user.save!
    user
  end

  def twitter
    @twitter ||= Twitter::REST::Client.new(
      consumer_key: ENV["TWITTER_KEY"],
      consumer_secret: ENV["TWITTER_SECRET"],
      access_token: self.oauth_token,
      access_token_secret: self.oauth_secret
      )
  end

  def add_twitter_friends
    results = twitter.friends.to_a
    results.each do |friend|
      self.friends.where(
        name: friend.screen_name,
        uid: friend.id.to_s
        ).first_or_create
    end
  end

  def facebook
    @facebook ||= Koala::Facebook::API.new(self.oauth_token)
  end

  def add_facebook_friends
    facebook.get_connection("me", "friends").each do |friend|
      self.friends.where(
        name: friend["name"],
        uid: friend["id"]
        ).first_or_create
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) << :oauth_token
      devise_parameter_sanitizer.for(:sign_up) << :oauth_secret
    end

end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController

  def index
    @friends = Friend.order(:name).where("name like ?", "%#{params[:term]}%")
    render json: @friends.map(&:name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_path, notice: "Signed in"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Signed out"
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def twitter
    @user = User.find_for_twitter_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => "Twitter") if is_navigational_format?
    else
      session["devise.twitter_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_url
    end
  end

  def google_oauth2
    @user = User.find_for_google_oauth(request.env["omniauth.auth"], current_user)
    @auth = request.env["omniauth.auth"]
    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => "Google") if is_navigational_format?
    else
      session["devise.google_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ReSafari</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="alerts">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
</div>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/welcome/index.html.erb
<div class="row">

<% if user_signed_in? %>
  Signed in as <%= current_user.name %>
  <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to "Sign in with Twitter", user_omniauth_authorize_path(:twitter) %><br />
  <%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %><br />
  <%#= link_to "Sign in with Google", user_omniauth_authorize_path(:google_oauth2) %>
<% end %>

<h1>Social Friend Finder</h1>
<p>Authorize your account above, and then start typing below to find friends from those networks</p>
<br />

<% if user_signed_in? %>
  <%= form_for :friend do |f| %>
    <%#= f.label :name %><br />
    <%= f.text_field :name, data: { autocomplete_url: friends_url } %>
    <%= f.submit "Add friend to list", id: "friend_submit" %>
  <% end %>

<br />
<br />

<ul class="friends_list">
  <li>FRIEND LIST</li>
</ul>
<% end %>
</div>